### ISSUE TITLE
Video is recorded at a different speed

### ISSUE THREAD

**Issue by vasukapoor20** [vahid-sb/LSL_Video_Acquisition#2]
Hi Vahid,
It seems to us that the video that gets saved in the folder after we stop running the code plays at a faster speed than the original recording. We first noticed this when we realized that the length of our lab recorder session didn't match with the video length. After using the lab recorder for around 3 hours, we ended up having a video recording that lasted only 1 hour 28 minutes.
Have you or someone else who used this code experienced this?
Thank you so much.

**Comment by vahid-sb** [comment]
Hi @vasukapoor20 
This is the first time I have been told about such an issue and never faced it when using it myself. To help, please let me know what OS and version of Python you use. And also, what video codecs are installed on your system? 
Also, you can do a couple of simple tests to help figure out what is going on. Firstly, the variable that controls the frame rate is ´fps´. You can set it manually to ´fps = 30´, and add a line like ´print("frames per second: ", fps)´ to the end of the main.py script to make sure it is not changed. Then please record a sample video for a fixed amount of time, like 2 minutes. Then please check the fps of the recorded video and its length. If all works well, you should have a two-minute video with an fps of 30. Based on your feedback I'd be able to help better.

**Comment by vasukapoor20** [comment]
Hi @vahid-sb thanks for your response.
I use Windows OS and am using Jupyter notebooks to run the python code, which has version 3.8.5.
The following codecs are installed on my system: 
![video_codecs](https://user-images.githubusercontent.com/82179039/229280680-4b1b8b4d-f21e-464b-91e1-b3a59b88372e.jpeg)

I did a sample test as you suggested. I set the fps to 30 and added the print statement. While recording, the printout remains to be 30. However, for a video recording of actually 2 minutes, which was measured exactly by recording a world clock, the video file length would only be 1 minute and 52 seconds. Within the properties of the video file, it does indicate that the frame rate is 30.
Thank you so much for your help.

**Comment by vasukapoor20** [comment]
Hi @vahid-sb thanks for your response.
I use Windows OS and am using Jupyter notebooks to run the python code, which has version 3.8.5.
The following codecs are installed on my system: 
![video_codecs](https://user-images.githubusercontent.com/82179039/229280680-4b1b8b4d-f21e-464b-91e1-b3a59b88372e.jpeg)

I did a sample test as you suggested. I set the fps to 30 and added the print statement. While recording, the printout remains to be 30. However, for a video recording of actually 2 minutes, which was measured exactly by recording a world clock, the video file length would only be 1 minute and 52 seconds. Within the properties of the video file, it does indicate that the frame rate is 30.
Thank you so much for your help.

**Comment by vahid-sb** [comment]
Thanks for the info @vasukapoor20 
Usually, it takes a few seconds between the time you run the Python script and the time the camera window appears. in other words, your video starts when the window shows up on your screen. And I suspect that explains the missing 8 seconds. To test that, you can point the camera to a clock when you run the script. Then write down the time when you run the script, call it t0. And then also when the window appears, we call it t1, and again when you close the window, we call it t2. Most probably your videos start showing at t1 and end at t2. 
Also, please note that the frame numbers in the xdf file start from the moment you start recording in the LSL Lab Recorder app. Hence, anything recorded or not recorded before you run the Lab recorder is not important, since you do not have time stamps for them in the xdf file to compare with other streams. 
I hope this could help.

**Comment by vahid-sb** [comment]
Also, as a separate note, better to run the script in the command prompt, not Jupyter.

**Comment by vasukapoor20** [comment]
Hello Vahid,

The method you described is exactly what we did. We pointed the camera to a world clock, thus when we ran the code the exact time when it started recording and stopped recording would be seen on the video. The time between the starting and stopping time seen in the video was 2 minutes, however, the length of the video was 1.52 minutes.
Now we changed the codec to MP4V and for short recordings, this problem got eliminated. However, when we have a 7-hour recording, the video recording is 5 seconds short of the actual time passed.
We will continue looking to see if we can find the error. If we do we will keep you up to date.

Kind regards,
Vasu Kapoor

**Comment by vahid-sb** [comment]
@vasukapoor20 did you write down the time on the clock when you started the python script and when the camera preview shows up? If you do, you'd see the video starts from the moment the preview screen shows up. 
I have done many recordings with this script, and never had the case that videos in the middle of a recording are arbitrarily missing. So, unless you find evidence to the contrary, you can safely use the script. 
If anything is still unclear for you, please let me know in the next few days, otherwise, I'd close this issue.
